name: Deploy to cloudtype
on:
  push:
    branches:
      - main

env:
  SPACE_NAME: dmsrkd1216
  PROJECT_NAME: toy-squads
  SERVICE_NAME: toy-squad-client

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUD_TYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUD_TYPE_TOKEN }}
          project: ${{ env.SPACE_NAME }}/${{ env.PROJECT_NAME }}
          stage: main
          yaml: |
            name: ${{ env.SERVICE_NAME  }}
            app: web
            options:
              docbase: /build
              nodeversion: 18
              spa: true
            context:
              git:
                url: git@github.com:${{ github.repository}}.git
                ref: ${{ github.ref }}
              preset: react
